/*
 * MimePost API Reference (Beta)
 * MimePost API for sending email.  You can find out more about MimePost at [https://mimepost.com](http://mimepost.com). For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@mimepost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mimepost.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApiResponseStatsDataTotalSummaryStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-20T12:32:16.156+05:30")
public class ApiResponseStatsDataTotalSummaryStatus {
  @SerializedName("count")
  private Integer count = null;

  @SerializedName("perc")
  private String perc = null;

  public ApiResponseStatsDataTotalSummaryStatus count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(value = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public ApiResponseStatsDataTotalSummaryStatus perc(String perc) {
    this.perc = perc;
    return this;
  }

   /**
   * Get perc
   * @return perc
  **/
  @ApiModelProperty(value = "")
  public String getPerc() {
    return perc;
  }

  public void setPerc(String perc) {
    this.perc = perc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiResponseStatsDataTotalSummaryStatus apiResponseStatsDataTotalSummaryStatus = (ApiResponseStatsDataTotalSummaryStatus) o;
    return Objects.equals(this.count, apiResponseStatsDataTotalSummaryStatus.count) &&
        Objects.equals(this.perc, apiResponseStatsDataTotalSummaryStatus.perc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, perc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiResponseStatsDataTotalSummaryStatus {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    perc: ").append(toIndentedString(perc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

