/*
 * MimePost API Reference (Beta)
 * MimePost API for sending email.  You can find out more about MimePost at [https://mimepost.com](http://mimepost.com). For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@mimepost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mimepost.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mimepost.model.ApiResponseAllWebhooksData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApiResponseAllWebhooks
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-20T12:32:16.156+05:30")
public class ApiResponseAllWebhooks {
  @SerializedName("success")
  private Integer success = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("data")
  private List<ApiResponseAllWebhooksData> data = null;

  public ApiResponseAllWebhooks success(Integer success) {
    this.success = success;
    return this;
  }

   /**
   * Success status, 0 for failed 1 for success
   * @return success
  **/
  @ApiModelProperty(example = "1", value = "Success status, 0 for failed 1 for success")
  public Integer getSuccess() {
    return success;
  }

  public void setSuccess(Integer success) {
    this.success = success;
  }

  public ApiResponseAllWebhooks message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(example = "Webhook found", value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ApiResponseAllWebhooks data(List<ApiResponseAllWebhooksData> data) {
    this.data = data;
    return this;
  }

  public ApiResponseAllWebhooks addDataItem(ApiResponseAllWebhooksData dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<ApiResponseAllWebhooksData>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(value = "")
  public List<ApiResponseAllWebhooksData> getData() {
    return data;
  }

  public void setData(List<ApiResponseAllWebhooksData> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiResponseAllWebhooks apiResponseAllWebhooks = (ApiResponseAllWebhooks) o;
    return Objects.equals(this.success, apiResponseAllWebhooks.success) &&
        Objects.equals(this.message, apiResponseAllWebhooks.message) &&
        Objects.equals(this.data, apiResponseAllWebhooks.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, message, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiResponseAllWebhooks {\n");
    
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

