/*
 * MimePost API Reference (Beta)
 * MimePost API for sending email.  You can find out more about MimePost at [https://mimepost.com](http://mimepost.com). For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@mimepost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mimepost.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApiResponseStatsDataGraphSummary
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-20T12:32:16.156+05:30")
public class ApiResponseStatsDataGraphSummary {
  @SerializedName("dates")
  private List<String> dates = null;

  @SerializedName("status_counts")
  private List<Integer> statusCounts = null;

  public ApiResponseStatsDataGraphSummary dates(List<String> dates) {
    this.dates = dates;
    return this;
  }

  public ApiResponseStatsDataGraphSummary addDatesItem(String datesItem) {
    if (this.dates == null) {
      this.dates = new ArrayList<String>();
    }
    this.dates.add(datesItem);
    return this;
  }

   /**
   * Get dates
   * @return dates
  **/
  @ApiModelProperty(value = "")
  public List<String> getDates() {
    return dates;
  }

  public void setDates(List<String> dates) {
    this.dates = dates;
  }

  public ApiResponseStatsDataGraphSummary statusCounts(List<Integer> statusCounts) {
    this.statusCounts = statusCounts;
    return this;
  }

  public ApiResponseStatsDataGraphSummary addStatusCountsItem(Integer statusCountsItem) {
    if (this.statusCounts == null) {
      this.statusCounts = new ArrayList<Integer>();
    }
    this.statusCounts.add(statusCountsItem);
    return this;
  }

   /**
   * Get statusCounts
   * @return statusCounts
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getStatusCounts() {
    return statusCounts;
  }

  public void setStatusCounts(List<Integer> statusCounts) {
    this.statusCounts = statusCounts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiResponseStatsDataGraphSummary apiResponseStatsDataGraphSummary = (ApiResponseStatsDataGraphSummary) o;
    return Objects.equals(this.dates, apiResponseStatsDataGraphSummary.dates) &&
        Objects.equals(this.statusCounts, apiResponseStatsDataGraphSummary.statusCounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dates, statusCounts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiResponseStatsDataGraphSummary {\n");
    
    sb.append("    dates: ").append(toIndentedString(dates)).append("\n");
    sb.append("    statusCounts: ").append(toIndentedString(statusCounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

