/*
 * MimePost API Reference (Beta)
 * MimePost API for sending email.  You can find out more about MimePost at [https://mimepost.com](http://mimepost.com). For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@mimepost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mimepost.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mimepost.model.EmailMergeVars;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * EmailTo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-20T12:32:16.156+05:30")
public class EmailTo {
  @SerializedName("email")
  private String email = null;

  @SerializedName("merge_vars")
  private List<EmailMergeVars> mergeVars = null;

  public EmailTo email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(example = "to@example.com", value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public EmailTo mergeVars(List<EmailMergeVars> mergeVars) {
    this.mergeVars = mergeVars;
    return this;
  }

  public EmailTo addMergeVarsItem(EmailMergeVars mergeVarsItem) {
    if (this.mergeVars == null) {
      this.mergeVars = new ArrayList<EmailMergeVars>();
    }
    this.mergeVars.add(mergeVarsItem);
    return this;
  }

   /**
   * Get mergeVars
   * @return mergeVars
  **/
  @ApiModelProperty(value = "")
  public List<EmailMergeVars> getMergeVars() {
    return mergeVars;
  }

  public void setMergeVars(List<EmailMergeVars> mergeVars) {
    this.mergeVars = mergeVars;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailTo emailTo = (EmailTo) o;
    return Objects.equals(this.email, emailTo.email) &&
        Objects.equals(this.mergeVars, emailTo.mergeVars);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, mergeVars);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailTo {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    mergeVars: ").append(toIndentedString(mergeVars)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

