/*
 * MimePost API Reference (Beta)
 * MimePost API for sending email.  You can find out more about MimePost at [https://mimepost.com](http://mimepost.com). For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@mimepost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import com.mimepost.ApiException;
import com.mimepost.model.AccountProfile;
import com.mimepost.model.AccountProfileResponse;
import com.mimepost.model.AccountSettings;
import com.mimepost.model.ModelApiResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountsApi
 */
@Ignore
public class AccountsApiTest {

    private final AccountsApi api = new AccountsApi();

    
    /**
     * Get account profile details
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accountProfileGetTest() throws ApiException {
        AccountProfileResponse response = api.accountProfileGet();

        // TODO: test validations
    }
    
    /**
     * Update account profile details
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accountProfilePostTest() throws ApiException {
        AccountProfile body = null;
        ModelApiResponse response = api.accountProfilePost(body);

        // TODO: test validations
    }
    
    /**
     * Get all the settings
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsGetTest() throws ApiException {
        AccountSettings response = api.settingsGet();

        // TODO: test validations
    }
    
    /**
     * Set a setting
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsPostTest() throws ApiException {
        AccountSettings body = null;
        ModelApiResponse response = api.settingsPost(body);

        // TODO: test validations
    }
    
}
