/*
 * MimePost API Reference (Beta)
 * MimePost API for sending email.  You can find out more about MimePost at [https://mimepost.com](http://mimepost.com). For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@mimepost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import com.mimepost.ApiException;
import com.mimepost.model.ApiResponseEmaillogs;
import com.mimepost.model.ApiResponseStats;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StatsApi
 */
@Ignore
public class StatsApiTest {

    private final StatsApi api = new StatsApi();

    
    /**
     * Get the logs of a particular date
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void emaillogsGetTest() throws ApiException {
        String startDate = null;
        String endDate = null;
        String status = null;
        String to = null;
        Integer page = null;
        Integer limit = null;
        ApiResponseEmaillogs response = api.emaillogsGet(startDate, endDate, status, to, page, limit);

        // TODO: test validations
    }
    
    /**
     * Get the summary of stats for a range of dates
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void statsGetTest() throws ApiException {
        String startDate = null;
        String endDate = null;
        ApiResponseStats response = api.statsGet(startDate, endDate);

        // TODO: test validations
    }
    
}
